"""empty message

Revision ID: 343de221c8b0
Revises: be6d722a8d64
Create Date: 2020-04-13 15:20:08.650254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343de221c8b0'
down_revision = 'be6d722a8d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('contacts1', sa.String(length=128), nullable=True))
    op.add_column('company', sa.Column('level', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'level')
    op.drop_column('company', 'contacts1')
    # ### end Alembic commands ###
