"""empty message

Revision ID: 3fd670110449
Revises: 
Create Date: 2020-04-18 15:50:52.691561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3fd670110449'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('info', sa.String(length=1000), nullable=True),
    sa.Column('credentials', sa.String(length=2000), nullable=True),
    sa.Column('register_capital', sa.String(length=20), nullable=True),
    sa.Column('industry_type', sa.Integer(), nullable=True),
    sa.Column('contact_person', sa.String(length=128), nullable=True),
    sa.Column('contacts', sa.String(length=128), nullable=True),
    sa.Column('contacts1', sa.String(length=128), nullable=True),
    sa.Column('recent_situation', sa.Text(length=256), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['industry_type'], ['industry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(length=256), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=128),
               nullable=False)
    op.create_foreign_key(None, 'roles', 'sys_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.alter_column('roles', 'name',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_table('records')
    op.drop_table('company')
    # ### end Alembic commands ###
