"""empty message

Revision ID: 5c2ba0f1b496
Revises: a520a25c76bb
Create Date: 2020-04-10 11:00:52.939549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c2ba0f1b496'
down_revision = 'a520a25c76bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_user', sa.Column('avatar', sa.String(length=256), nullable=True))
    op.add_column('sys_user', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('sys_user', sa.Column('role', sa.String(length=64), nullable=True))
    op.alter_column('sys_user', 'password',
               existing_type=mysql.VARCHAR(length=256),
               comment=None,
               existing_comment='密码',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('sys_user', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='手机',
               existing_nullable=True)
    op.alter_column('sys_user', 'username',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_user', 'username',
               existing_type=mysql.VARCHAR(length=128),
               comment='用户名',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('sys_user', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               comment='手机',
               existing_nullable=True)
    op.alter_column('sys_user', 'password',
               existing_type=mysql.VARCHAR(length=256),
               comment='密码',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.drop_column('sys_user', 'role')
    op.drop_column('sys_user', 'name')
    op.drop_column('sys_user', 'avatar')
    # ### end Alembic commands ###
