"""empty message

Revision ID: e9174ceef5e8
Revises: 343de221c8b0
Create Date: 2020-04-14 22:09:14.099739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9174ceef5e8'
down_revision = '343de221c8b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('credentials', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'credentials')
    # ### end Alembic commands ###
